### ISSUE TITLE
databus example problem  Cannot bind to URL 

### ISSUE THREAD

**Issue by godlike110** [linkedin/databus#75]
when i set  databus.relay.container.jmx.rmiEnabled=true in relay_or_person.properties , it is gose wrong when starting. like this:  how can id deal with it

2016-03-13 21:18:40,396 +3289 [main] (INFO) {DatabusRelayMain} done initializing producers
2016-03-13 21:18:40,441 +3334 [main] (INFO) {ServerContainer} Saving port number in /Users/zhiwei/workspace/mydatabus/./containerPortNum_9786
2016-03-13 21:18:40,441 +3334 [main] (INFO) {ServerContainer} Serving container 9786 HTTP listener on port 11115
2016-03-13 21:18:40,569 +3462 [main] (ERROR) {ServerContainer} Unable to start JMX server connector
java.io.IOException: Cannot bind to URL [rmi://localhost:1099/jmxrmi9988]: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused]
	at javax.management.remote.rmi.RMIConnectorServer.newIOException(RMIConnectorServer.java:826)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:431)
	at com.linkedin.databus2.core.container.netty.ServerContainer.doStart(ServerContainer.java:443)
	at com.linkedin.databus.container.netty.HttpRelay.doStart(HttpRelay.java:275)
	at com.linkedin.databus2.relay.DatabusRelayMain.doStart(DatabusRelayMain.java:307)
	at com.linkedin.databus2.core.container.netty.ServerContainer.start(ServerContainer.java:369)
	at com.linkedin.databus2.core.container.netty.ServerContainer.startAndBlock(ServerContainer.java:360)
	at server.PersonRelayServer.main(PersonRelayServer.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused]
	at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:143)
	at com.sun.jndi.toolkit.url.GenericURLContext.bind(GenericURLContext.java:226)
	at javax.naming.InitialContext.bind(InitialContext.java:419)
	at javax.management.remote.rmi.RMIConnectorServer.bind(RMIConnectorServer.java:643)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:426)
	... 11 more
Caused by: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:341)
	at sun.rmi.registry.RegistryImpl_Stub.bind(Unknown Source)
	at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:137)
	... 15 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:147)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 20 more
2016-03-13 21:18:40,571 +3464 [main] (INFO) {DatabusRelayMain} Starting. Producers are :{{"id":1,"name":"person"}=com.linkedin.databus2.producers.OpenReplicatorEventProducer@4f11241e}

**Comment by tanziqi** [comment]
you should running "rmiregistry" in console, then run databus-client.
you can see:
https://stackoverflow.com/questions/31471467/cant-start-jmxconnectorserver 
https://zhubingxu.me/2017/12/19/databus-demo/
